name: chladni
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hfdf4475_7
  - ca-certificates=2024.7.4=h8857fd0_0
  - libffi=3.4.2=h0d85af4_5
  - libsqlite=3.46.0=h1b8f9f3_0
  - libzlib=1.3.1=h87427d6_1
  - ncurses=6.5=h5846eda_0
  - openssl=3.3.1=h87427d6_2
  - pip=24.2=pyhd8ed1ab_0
  - python=3.9.19=h7a9c478_0_cpython
  - readline=8.2=h9e318b2_1
  - setuptools=72.1.0=pyhd8ed1ab_0
  - tk=8.6.13=h1abcd95_1
  - tzdata=2024a=h0c530f3_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - pip:
      - asgiref==3.8.1
      - django==4.2.15
      - djangorestframework==3.15.2
      - imageio==2.34.2
      - lazy-loader==0.4
      - networkx==3.2.1
      - numpy==2.0.1
      - packaging==24.1
      - pillow==10.4.0
      - scikit-image==0.24.0
      - scipy==1.13.1
      - sqlparse==0.5.1
      - tifffile==2024.8.10
      - typing-extensions==4.12.2
prefix: /Users/nicolas/opt/anaconda3/envs/chladni
